name: pytorch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.4.13=h06a4308_1
  - cudatoolkit=11.1.74=h6bb024c_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2020.2=254
  - ipython_genutils=0.2.0=py37_0
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.0=h27cfd23_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.7.2=hbbd107a_1
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1k=h27cfd23_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pip=19.3.1=py37_0
  - ptyprocess=0.6.0=py37_0
  - python=3.7.6=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=44.0.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchaudio=0.8.1=py37
  - wcwidth=0.2.5=py_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.2=he6710b0_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.14.1
    - addict==2.4.0
    - aiohttp==3.7.4.post0
    - alembic==1.6.5
    - antlr4-python3-runtime==4.8
    - anyio==3.3.4
    - appdirs==1.4.4
    - argcomplete==2.0.0
    - argon2-cffi==21.1.0
    - astroid==2.5.6
    - async-generator==1.10
    - async-timeout==3.0.1
    - attrs==21.2.0
    - autopep8==1.5.7
    - av==8.0.3
    - babel==2.9.1
    - bert-score==0.3.10
    - black==21.4b2
    - bleach==4.1.0
    - cached-property==1.5.2
    - cachetools==4.2.4
    - certifi==2021.10.8
    - cffi==1.15.0
    - chardet==4.0.0
    - charset-normalizer==2.0.7
    - cityscapesscripts==2.2.0
    - click==8.0.0
    - cliff==3.8.0
    - clip==1.0
    - cloudpickle==1.6.0
    - cmaes==0.8.2
    - cmd2==2.1.1
    - colorama==0.4.4
    - coloredlogs==15.0.1
    - colorlog==5.0.1
    - configparser==5.0.2
    - cycler==0.10.0
    - cython==0.29.23
    - debugpy==1.5.0
    - decorator==5.1.0
    - deepspeed==0.3.16
    - defusedxml==0.7.1
    - deprecated==1.2.12
    - detectron2==0.6
    - dill==0.3.4
    - docker-pycreds==0.4.0
    - easydict==1.9
    - einops==0.4.1
    - entrypoints==0.3
    - filelock==3.0.12
    - filetype==1.0.8
    - fire==0.4.0
    - fsspec==2021.10.1
    - ftfy==6.0.3
    - future==0.18.2
    - fvcore==0.1.5.post20211023
    - gdown==3.13.0
    - gitdb==4.0.7
    - gitpython==3.1.14
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - gputil==1.4.0
    - greenlet==1.1.0
    - grpcio==1.41.0
    - h5py==3.2.1
    - hiddenlayer==0.3
    - huggingface-hub==0.0.17
    - humanfriendly==10.0
    - humanize==3.5.0
    - hydra-core==1.1.1
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==4.0.1
    - importlib-resources==5.1.2
    - iopath==0.1.9
    - ipykernel==6.4.1
    - ipython==7.28.0
    - ipywidgets==7.6.5
    - isort==5.9.1
    - jedi==0.18.0
    - jinja2==3.0.2
    - joblib==1.0.1
    - json5==0.9.6
    - jsonschema==4.1.0
    - jupyter-client==7.0.6
    - jupyter-core==4.8.1
    - jupyter-server==1.13.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.1
    - kornia==0.6.3
    - lazy-object-proxy==1.6.0
    - llvmlite==0.33.0
    - lmdb==1.2.1
    - mako==1.1.4
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==2.2.0
    - matplotlib-inline==0.1.3
    - mccabe==0.6.1
    - medpy==0.4.0
    - mistune==0.8.4
    - mmcls==0.21.0
    - mmcv-full==1.4.0
    - monai==0.5.2
    - mpi4py==3.0.3
    - multidict==5.1.0
    - multiscaledeformableattention==1.0
    - mypy-extensions==0.4.3
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - nibabel==3.2.1
    - ninja==1.10.0.post2
    - nltk==3.6.2
    - nose==1.3.7
    - notebook==6.4.0
    - numba==0.50.0
    - numpy==1.18.0
    - nvidia-htop==1.0.3
    - oauthlib==3.1.0
    - omegaconf==2.1.1
    - opencv-python==4.5.2.52
    - optuna==2.8.0
    - packaging==21.0
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pbr==5.6.0
    - pillow==8.4.0
    - portalocker==2.3.2
    - prettytable==2.1.0
    - prometheus-client==0.11.0
    - promise==2.3
    - prompt-toolkit==3.0.20
    - protobuf==3.16.0
    - psutil==5.8.0
    - ptflops==0.6.8
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocoevalcap==1.2
    - pycocotools==2.0.2
    - pycodestyle==2.7.0
    - pycparser==2.20
    - pydantic==1.9.0
    - pydensecrf==1.0rc2
    - pydeprecate==0.3.0
    - pydot==1.4.2
    - pygments==2.10.0
    - pylint==2.8.3
    - pyparsing==2.4.7
    - pyperclip==1.8.2
    - pyquaternion==0.9.9
    - pyrsistent==0.18.0
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - python-graphviz==0.16
    - pytorch-ignite==0.4.7
    - pytorch-lightning==1.3.1
    - pytz==2021.3
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - regex==2021.7.6
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - ruamel-yaml==0.17.17
    - ruamel-yaml-clib==0.2.6
    - sacremoses==0.0.45
    - scikit-image==0.18.1
    - scikit-learn==0.21.3
    - scipy==1.7.3
    - seaborn==0.11.1
    - send2trash==1.7.1
    - sentencepiece==0.1.96
    - sentry-sdk==1.1.0
    - sh==1.14.2
    - shortuuid==1.0.1
    - simpleitk==1.2.4
    - simplejson==3.17.5
    - six==1.16.0
    - slackclient==2.9.3
    - smmap==4.0.0
    - sniffio==1.2.0
    - sqlalchemy==1.4.20
    - stevedore==3.3.0
    - subprocess32==3.5.4
    - survae==0.1
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==1.8
    - termcolor==1.1.0
    - terminado==0.10.1
    - terminaltables==3.1.0
    - test-tube==0.7.5
    - testpath==0.5.0
    - tifffile==2021.4.8
    - timm==0.5.4
    - tokenizers==0.10.3
    - toml==0.10.2
    - torch==1.9.0+cu111
    - torch-encoding==1.2.2b20220616
    - torch-tb-profiler==0.2.0
    - torchinfo==0.1.5
    - torchio==0.18.39
    - torchmetrics==0.3.2
    - torchsummary==1.5.1
    - torchvision==0.10.0
    - tornado==6.1
    - tqdm==4.48.2
    - traitlets==5.1.0
    - transformers==4.10.3
    - typed-ast==1.4.3
    - typing==3.7.4.3
    - typing-extensions==3.10.0.2
    - urllib3==1.26.4
    - voila==0.3.0
    - wandb==0.10.30
    - warmup-scheduler==0.3.2
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - websockets==10.1
    - werkzeug==2.0.0
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - yacs==0.1.8
    - yapf==0.31.0
    - yarl==1.6.3
    - zipp==3.4.1
prefix: /home/kashu/miniconda3/envs/pytorch
